site_name: CODE User Guide
site_url: https://tfhrc-ai-code.github.io/AI-CODE/
repo_url: https://github.com/TFHRC-AI-CODE/AI-CODE
repo_name: Edit on GitHub

theme:
  name: readthedocs
  highlightjs: true

nav:
  - INTRODUCTION:
      - Overview: index.md
  - CASE STUDIES:
      - Infrastructure: case-studies/infrastructure/deep-learning-for-impact-echo.md
      - Safety:
  - CONTRIBUTING:
      - Contribution Guide: contribution-guide.md
      - Case Study Template: templates/case-study-template.md
