site_name: CODE User Guide
site_url: https://tfhrc-ai-code.github.io/AI-CODE/
edit_uri: ""

theme:
  name: readthedocs
  highlightjs: true

nav:
  - INTRODUCTION:
      - Overview: index.md
  - CASE STUDIES:
      - Infrastructure:
          - Deep Learning for Impact Echo: case-studies/infrastructure/deep-learning-for-impact-echo.md
          - Explainable AI: case-studies/infrastructure/explainable-AI-for-impact-echo.md
          - Pavement Fatigue Life Ratio: case-studies/infrastructure/Pavement-FLR-Models.md
      - Safety: case-studies/safety/placeholder.md
  - CONTRIBUTING:
      - Contribution Guide: contribution-guide.md
      - Case Study Template: templates/case-study-template.md
